//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpiderU {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIMessageResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpiderU.UIMessageResource", typeof(UIMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Null or invalid argument  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIMSGARGEXCEPTION {
            get {
                return ResourceManager.GetString("UIMSGARGEXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t open Oscilloscope as USB PHY device. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIMSGCANTOPENUSBPHY {
            get {
                return ResourceManager.GetString("UIMSGCANTOPENUSBPHY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internal data consisitency error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIMSGDATAINCONSIST {
            get {
                return ResourceManager.GetString("UIMSGDATAINCONSIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Record length exceeds Excel row count limit. Can&apos;t make Excel file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIMSGEXCELRANGEOVER {
            get {
                return ResourceManager.GetString("UIMSGEXCELRANGEOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oscilloscope ID string is illegal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIMSGILLEGALID {
            get {
                return ResourceManager.GetString("UIMSGILLEGALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of USB Endpoint is illegal. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIMSGILLEGALNUMEP {
            get {
                return ResourceManager.GetString("UIMSGILLEGALNUMEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internal illegal function call に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIMSGINTILLEGALARG {
            get {
                return ResourceManager.GetString("UIMSGINTILLEGALARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IO error occured に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIMSGIOEXCEPTION {
            get {
                return ResourceManager.GetString("UIMSGIOEXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No oscilloscope found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIMSGNOSCOPE {
            get {
                return ResourceManager.GetString("UIMSGNOSCOPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync all oscilloscope option is checked, but not all osilloscope record length and sampling time is identical. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIMSGNOTSYNCABLE {
            get {
                return ResourceManager.GetString("UIMSGNOTSYNCABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path too long に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIMSGPATHTOOLONG {
            get {
                return ResourceManager.GetString("UIMSGPATHTOOLONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIMSGREADYSTATE {
            get {
                return ResourceManager.GetString("UIMSGREADYSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Security exception occured に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIMSGSECURITYEXCEPTION {
            get {
                return ResourceManager.GetString("UIMSGSECURITYEXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transferring data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIMSGTRANSFERSTATE {
            get {
                return ResourceManager.GetString("UIMSGTRANSFERSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown error occured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIMSGUNKNOWN {
            get {
                return ResourceManager.GetString("UIMSGUNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USB read error occured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UIMSGUSBREADERROR {
            get {
                return ResourceManager.GetString("UIMSGUSBREADERROR", resourceCulture);
            }
        }
    }
}
